import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BadgeIndianRupee, Bot, Check, FileText, MessageCircle, ScanSearch, Send, ShieldCheck, Sparkles, WalletCards } from "lucide-react";
import { Mark } from "@/components/mark";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({ component: Landing });

const loop = [
  { icon: MessageCircle, label: "Understand", copy: "Read messy Hindi, Hinglish and English." },
  { icon: ScanSearch, label: "Retrieve", copy: "Match customers, catalog, pricing and invoice context." },
  { icon: Bot, label: "Decide", copy: "Select the next permitted operational action." },
  { icon: Send, label: "Act & verify", copy: "Execute safely, verify outcomes, update state." },
];
const proof = ["Intent classification and structured extraction", "Customer, product, price and invoice retrieval", "Policy-controlled actions with human approval boundaries", "Compact, auditable event traces — never hidden reasoning"];

function Landing() {
  return <main className="min-h-dvh bg-bg">
    <header className="landing-reveal landing-reveal-1 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8">
      <Link to="/" className="flex items-center gap-2.5" aria-label="VYRA home"><Mark className="size-9 text-primary" /><span className="font-display text-2xl tracking-tight">VYRA</span></Link>
      <nav className="hidden items-center gap-6 text-sm text-muted md:flex"><a href="#how-it-works" className="transition-colors hover:text-fg">How it works</a><a href="#demo" className="transition-colors hover:text-fg">Product</a><a href="#trust" className="transition-colors hover:text-fg">Trust</a></nav>
      <Button asChild size="sm"><Link to="/demo">Open live demo <ArrowRight className="size-4" /></Link></Button>
    </header>
    <section className="mx-auto max-w-7xl px-5 pb-16 pt-6 sm:px-8 sm:pb-24 sm:pt-12"><div className="landing-hero landing-reveal landing-reveal-2 relative overflow-hidden rounded-2xl border border-border bg-surface shadow-border"><img src="/showcase/vyra-hero.png" alt="Textile business desk with a chat-enabled phone" className="landing-hero-image absolute inset-0 h-full w-full object-cover object-right" /><div className="landing-hero-wash absolute inset-0" /><div className="relative max-w-2xl px-6 py-16 sm:px-12 sm:py-24 lg:px-16 lg:py-28"><div className="landing-reveal landing-reveal-3 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-surface/90 px-3 py-1.5 text-xs font-medium text-primary shadow-border"><Sparkles className="size-3.5" /> India-first revenue operations agent</div><h1 className="landing-reveal landing-reveal-4 mt-6 font-display text-4xl leading-[0.96] tracking-[-0.05em] sm:text-6xl lg:text-7xl">The conversation is where revenue happens.</h1><p className="landing-reveal landing-reveal-5 mt-6 max-w-xl text-base leading-7 text-muted sm:text-lg">VYRA turns WhatsApp conversations into structured orders, invoice drafts, payment visibility, and the next safe action — so small businesses recover more cash without changing how they work.</p><div className="landing-reveal landing-reveal-6 mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/demo">See the agent in action <ArrowRight className="size-4" /></Link></Button><Button asChild size="lg" variant="secondary"><Link to="/recovery">Find stuck revenue</Link></Button></div><p className="landing-reveal landing-reveal-7 mt-5 text-xs text-muted">Deterministic demo mode · no WhatsApp, UPI, or bank credentials required</p></div></div></section>
    <section id="how-it-works" className="border-y border-border bg-surface"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20"><p className="text-xs font-medium tracking-[0.16em] text-primary uppercase">The VYRA loop</p><div className="mt-3 flex flex-wrap items-end justify-between gap-5"><h2 className="max-w-2xl font-display text-4xl sm:text-5xl">From a chat message to a verified business outcome.</h2><p className="max-w-sm text-sm leading-6 text-muted">Not a generic chatbot. A revenue agent that uses business context, operates inside policy, and records what happened.</p></div><div className="mt-10 grid gap-3 md:grid-cols-4">{loop.map((step, index) => <article key={step.label} className={`landing-step landing-step-${index + 1} relative rounded-xl border border-border bg-bg p-5`}><span className="font-mono text-xs text-muted">0{index + 1}</span><step.icon className="mt-8 size-5 text-primary" /><h3 className="mt-4 font-display text-2xl">{step.label}</h3><p className="mt-2 text-sm leading-6 text-muted">{step.copy}</p>{index < loop.length - 1 ? <ArrowRight className="absolute -right-5 top-1/2 z-10 hidden size-5 bg-surface text-primary md:block" /> : null}</article>)}</div></div></section>
    <section id="demo" className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><div className="grid items-center gap-10 lg:grid-cols-2"><div><p className="text-xs font-medium tracking-[0.16em] text-primary uppercase">A demo judges can understand in minutes</p><h2 className="mt-3 font-display text-4xl sm:text-5xl">Show the complete agent loop, not a mockup.</h2><p className="mt-5 max-w-xl leading-7 text-muted">Start with a real-world Hinglish order. VYRA classifies intent, extracts items, retrieves business context, selects the next action, and exposes only concise audit events.</p><ul className="mt-7 space-y-3">{proof.map((item) => <li key={item} className="flex gap-3 text-sm"><span className="mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full bg-primary-soft text-primary"><Check className="size-3" /></span>{item}</li>)}</ul><Button asChild className="mt-8"><Link to="/demo">Launch Demo Studio <ArrowRight className="size-4" /></Link></Button></div><div className="rounded-2xl border border-border bg-surface p-2 shadow-border"><img src="/showcase/order-extraction.png" alt="VYRA structured order extraction interface" className="w-full rounded-xl" /></div></div></section>
    <section className="border-y border-border bg-primary text-primary-fg"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 sm:py-20 lg:grid-cols-[1.1fr_1fr]"><div><p className="text-xs font-medium tracking-[0.16em] text-sidebar-muted uppercase">Revenue recovery</p><h2 className="mt-3 font-display text-4xl sm:text-5xl">Ask one question: where is my money stuck?</h2><p className="mt-5 max-w-xl leading-7 text-sidebar-muted">VYRA reviews outstanding invoices, brings back the relevant conversation context, prioritizes the account needing attention, drafts a tailored follow-up, and safely records the result.</p><Button asChild variant="secondary" className="mt-8"><Link to="/recovery">Run Revenue Recovery <BadgeIndianRupee className="size-4" /></Link></Button></div><div className="rounded-2xl bg-primary-fg/10 p-2 ring-1 ring-white/10"><img src="/showcase/recovery.png" alt="VYRA revenue recovery workspace" className="w-full rounded-xl" /></div></div></section>
    <section id="trust" className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><div className="grid gap-8 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="text-xs font-medium tracking-[0.16em] text-primary uppercase">Built for responsible action</p><h2 className="mt-3 font-display text-4xl sm:text-5xl">Useful autonomy, clear boundaries.</h2><p className="mt-5 max-w-xl leading-7 text-muted">The product keeps irreversible or sensitive actions outside the demo. Ambiguous messages are held for review. Every simulated action is traceable.</p></div><div className="grid gap-3 sm:grid-cols-2"><Trust icon={ShieldCheck} title="Human approval" copy="Inquiries, ambiguity, and sensitive actions remain review-gated." /><Trust icon={FileText} title="Auditable events" copy="Tools, structured results, decisions, and outcomes are visible." /><Trust icon={WalletCards} title="Sandbox execution" copy="Demo delivery and payment flows never touch real credentials." /><Trust icon={ScanSearch} title="Business context" copy="Decisions use outstanding invoices, messages, products, and pricing." /></div></div></section>
    <footer className="border-t border-border bg-surface"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-7 text-sm sm:px-8"><div className="flex items-center gap-2"><Mark className="size-6 text-primary" /><span className="font-display text-lg">VYRA</span><span className="text-muted">The AI revenue agent for WhatsApp-first businesses.</span></div><div className="flex gap-5 text-muted"><Link to="/demo" className="hover:text-fg">Demo</Link><Link to="/recovery" className="hover:text-fg">Recovery</Link><Link to="/desk" className="hover:text-fg">Workspace</Link></div></div></footer>
  </main>;
}
function Trust({ icon: Icon, title, copy }: { icon: typeof ShieldCheck; title: string; copy: string }) { return <article className="rounded-xl border border-border bg-surface p-5 shadow-border"><Icon className="size-5 text-primary" /><h3 className="mt-6 font-display text-2xl">{title}</h3><p className="mt-2 text-sm leading-6 text-muted">{copy}</p></article>; }
